// Code generated by qtc from "styleTag.html". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

// arsts

//line markdown/styleTag.html:2
package markdown

//line markdown/styleTag.html:2
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line markdown/styleTag.html:2
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line markdown/styleTag.html:2
func streamaddStyleTag(qw422016 *qt422016.Writer, styles []string, body string) {
//line markdown/styleTag.html:2
	qw422016.N().S(`
<style>`)
//line markdown/styleTag.html:3
	for _, style := range styles {
//line markdown/styleTag.html:3
		qw422016.E().S(style)
//line markdown/styleTag.html:3
	}
//line markdown/styleTag.html:3
	qw422016.N().S(`</style>
`)
//line markdown/styleTag.html:4
	qw422016.N().S(body)
//line markdown/styleTag.html:4
	qw422016.N().S(`
`)
//line markdown/styleTag.html:5
}

//line markdown/styleTag.html:5
func writeaddStyleTag(qq422016 qtio422016.Writer, styles []string, body string) {
//line markdown/styleTag.html:5
	qw422016 := qt422016.AcquireWriter(qq422016)
//line markdown/styleTag.html:5
	streamaddStyleTag(qw422016, styles, body)
//line markdown/styleTag.html:5
	qt422016.ReleaseWriter(qw422016)
//line markdown/styleTag.html:5
}

//line markdown/styleTag.html:5
func addStyleTag(styles []string, body string) string {
//line markdown/styleTag.html:5
	qb422016 := qt422016.AcquireByteBuffer()
//line markdown/styleTag.html:5
	writeaddStyleTag(qb422016, styles, body)
//line markdown/styleTag.html:5
	qs422016 := string(qb422016.B)
//line markdown/styleTag.html:5
	qt422016.ReleaseByteBuffer(qb422016)
//line markdown/styleTag.html:5
	return qs422016
//line markdown/styleTag.html:5
}
