// Code generated by qtc from "styleTag.html". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line markdown/styleTag.html:1
package markdown

//line markdown/styleTag.html:1
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line markdown/styleTag.html:1
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line markdown/styleTag.html:1
func streamaddStyleTag(qw422016 *qt422016.Writer, styles []string, cssLink string, body string) {
//line markdown/styleTag.html:1
	streamaddCssLink(qw422016, cssLink)
//line markdown/styleTag.html:1
	qw422016.N().S(`<style>`)
//line markdown/styleTag.html:1
	for _, style := range styles {
//line markdown/styleTag.html:1
		qw422016.E().S(style)
//line markdown/styleTag.html:1
	}
//line markdown/styleTag.html:1
	qw422016.N().S(`</style>
`)
//line markdown/styleTag.html:2
	qw422016.N().S(body)
//line markdown/styleTag.html:2
	qw422016.N().S(`
`)
//line markdown/styleTag.html:3
}

//line markdown/styleTag.html:3
func writeaddStyleTag(qq422016 qtio422016.Writer, styles []string, cssLink string, body string) {
//line markdown/styleTag.html:3
	qw422016 := qt422016.AcquireWriter(qq422016)
//line markdown/styleTag.html:3
	streamaddStyleTag(qw422016, styles, cssLink, body)
//line markdown/styleTag.html:3
	qt422016.ReleaseWriter(qw422016)
//line markdown/styleTag.html:3
}

//line markdown/styleTag.html:3
func addStyleTag(styles []string, cssLink string, body string) string {
//line markdown/styleTag.html:3
	qb422016 := qt422016.AcquireByteBuffer()
//line markdown/styleTag.html:3
	writeaddStyleTag(qb422016, styles, cssLink, body)
//line markdown/styleTag.html:3
	qs422016 := string(qb422016.B)
//line markdown/styleTag.html:3
	qt422016.ReleaseByteBuffer(qb422016)
//line markdown/styleTag.html:3
	return qs422016
//line markdown/styleTag.html:3
}

//line markdown/styleTag.html:5
func streamaddCssLink(qw422016 *qt422016.Writer, cssLink string) {
//line markdown/styleTag.html:5
	if cssLink != "" {
//line markdown/styleTag.html:5
		qw422016.N().S(`<link rel="stylesheet" href="`)
//line markdown/styleTag.html:5
		qw422016.E().S(cssLink)
//line markdown/styleTag.html:5
		qw422016.N().S(`">`)
//line markdown/styleTag.html:5
	}
//line markdown/styleTag.html:5
}

//line markdown/styleTag.html:5
func writeaddCssLink(qq422016 qtio422016.Writer, cssLink string) {
//line markdown/styleTag.html:5
	qw422016 := qt422016.AcquireWriter(qq422016)
//line markdown/styleTag.html:5
	streamaddCssLink(qw422016, cssLink)
//line markdown/styleTag.html:5
	qt422016.ReleaseWriter(qw422016)
//line markdown/styleTag.html:5
}

//line markdown/styleTag.html:5
func addCssLink(cssLink string) string {
//line markdown/styleTag.html:5
	qb422016 := qt422016.AcquireByteBuffer()
//line markdown/styleTag.html:5
	writeaddCssLink(qb422016, cssLink)
//line markdown/styleTag.html:5
	qs422016 := string(qb422016.B)
//line markdown/styleTag.html:5
	qt422016.ReleaseByteBuffer(qb422016)
//line markdown/styleTag.html:5
	return qs422016
//line markdown/styleTag.html:5
}
